structuresVersion=3.6.0

allureVersion=2.32.0
antlrVersion=4.13.1
aspectJVersion=1.9.22.1
apacheCommonsLangVersion=3.20.0
apacheCommonsTextVersion=1.15.0
caffeineVersion=3.1.8
commonsCompressVersion=1.27.1
commonsIoVersion=2.21.0
continuumVersion=3.1.0-SNAPSHOT
elasticClientVersion=8.18.1
graphQlFederationJvmVersion=5.3.0
graphQlJavaExtendedScalarsVersion=22.0
graphQlJavaVersion=22.3
groovyVersion=4.0.26
igniteVersion=2.18.0
jakartaAnnotationVersion=3.0.0
jreleaserVersion=1.21.0
jsonwebtokenVersion=0.12.6
otelBomVersion=1.57.0
otelInstrumentationBomVersion=2.23.0
lombokPluginVersion=9.1.0
nettyVersion=4.1.119.Final
luceneVersion=8.11.4
slugifyVersion=3.0.7
springAiVersion=2.0.1
springBootVersion=4.0.2
springDependencyManagementVersion=1.1.7
swaggerCoreVersion=2.2.27
testContainersVersion=1.20.4
toolsJacksonVersion=3.0.3
vertxVersion=5.1.4
vertxStompLiteVersion=6.0.0
vertxCompletableFutureVersion=0.1.2
