structuresVersion=3.6.2

allureVersion=2.35.5
aspectJVersion=1.9.25
apacheCommonsLangVersion=3.20.0
apacheCommonsTextVersion=1.15.0
commonsIoVersion=2.22.0
continuumVersion=3.1.0
elasticClientVersion=8.19.21
graphQlFederationJvmVersion=7.0.0
graphQlJavaExtendedScalarsVersion=24.0
graphQlJavaVersion=26.1
igniteVersion=2.18.0
jreleaserVersion=1.26.0
jsonwebtokenVersion=0.13.0
otelBomVersion=1.65.0
otelInstrumentationBomVersion=2.31.1
lombokPluginVersion=9.5.0
nettyVersion=4.2.18.Final
slugifyVersion=3.0.7
springAiVersion=2.0.1
springBootVersion=4.1.1
springDependencyManagementVersion=1.1.7
swaggerCoreVersion=2.2.55
testcontainersKeycloakVersion=4.3.1
vertxVersion=5.1.8
vertxStompLiteVersion=6.0.0
