import path from 'path'
import {ITask} from '../ITask.js'
import {ITaskGenerator} from '../ITaskGenerator.js'
import {EntityDefinitionLoader} from '../../utils/EntityDefinitionLoader.js'
import {ConnectionInfo, Continuum} from '@kinotic/continuum-client'
import {Project, ProjectType, Structure, Structures} from '@kinotic/structures-api'
import {ObjectC3Type} from '@kinotic/continuum-idl'

/**
 * Creates and publishes the `load-testing.person` structure the people load tests write to and read
 * from, when it does not exist yet. An existing structure is left alone, data included.
 */
export class CreatePersonStructureTaskGenerator implements ITaskGenerator {
    public static readonly APPLICATION_ID = 'load-testing'
    public static readonly STRUCTURE_NAME = 'Person'

    private readonly tasks: ITask[]
    private currentTaskIndex = 0
    private definitions: Map<string, ObjectC3Type> = new Map()

    constructor(connectionInfoSupplier: () => Promise<ConnectionInfo>) {
        const applicationId = CreatePersonStructureTaskGenerator.APPLICATION_ID
        const name = CreatePersonStructureTaskGenerator.STRUCTURE_NAME
        this.tasks = [
            {
                name: () => 'Connect to Continuum',
                execute: async () => {
                    await Continuum.connect(await connectionInfoSupplier())
                }
            },
            {
                name: () => `Create ${applicationId}.${name.toLowerCase()} if missing`,
                execute: async () => {
                    const structureService = Structures.getStructureService()
                    const structureId = `${applicationId}.${name.toLowerCase()}`
                    const existing = await structureService.findById(structureId)
                    if (existing) {
                        if (!existing.published) {
                            await structureService.publish(existing.id!)
                        }
                        console.log(`Structure ${structureId} already exists`)
                        return
                    }

                    await Structures.getApplicationService().createApplicationIfNotExist(applicationId, 'Load Testing')
                    let project = new Project(null, applicationId, 'People', 'People load tests')
                    project.sourceOfTruth = ProjectType.TYPESCRIPT
                    project = await Structures.getProjectService().createProjectIfNotExist(project)

                    const loader = new EntityDefinitionLoader(applicationId,
                                                              path.join(__dirname, '../../entity/domain/people'),
                                                              path.join(__dirname, '../../services'))
                    this.definitions = await loader.loadDefinitions()
                    const definition = this.definitions.get(name.toLowerCase())
                    if (!definition) {
                        throw new Error(`No entity definition for ${name}`)
                    }

                    const structure = new Structure(applicationId, project.id as string, name, definition,
                                                    'People generated by the load tests')
                    const saved = await structureService.create(structure)
                    await structureService.publish(saved.id!)
                    console.log(`Created and published ${structureId}`)
                }
            },
            {
                name: () => 'Disconnect from Continuum',
                execute: async () => {
                    await Continuum.disconnect()
                }
            }
        ]
    }

    getNextTask(): ITask {
        if (this.currentTaskIndex >= this.tasks.length) {
            throw new Error('No more tasks available')
        }
        return this.tasks[this.currentTaskIndex++]
    }

    hasMoreTasks(): boolean {
        return this.currentTaskIndex < this.tasks.length
    }
}
